//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Entity_Speed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oilfield
    {
        public Oilfield()
        {
            this.Well = new HashSet<Well>();
        }
    
        public string Name { get; set; }
        public Nullable<int> OilResolv { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<Well> Well { get; set; }
    }
}
