//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Entity_Speed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Well
    {
        public int ID { get; set; }
        public Nullable<int> IDOilfield { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Debit { get; set; }
        public string Pump { get; set; }
    
        public virtual Oilfield Oilfield { get; set; }
    }
}
